name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # don't cancel other jobs if one fails
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Build & publish
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true